### ISSUE TITLE
Remove HCC support from BLT

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/blt#535] opened 2021-10-29 03:37 UTC
HCC is deprecated; we should remove support for HCC from blt.

See: https://rocmdocs.amd.com/en/latest/Installation_Guide/HCC-Compiler.html

Related: #534

**Comment by white238** [comment] 2022-04-28 22:33
Fixed in #579 and a duplicate of #426

**Closed by white238** 2022-04-28 22:33 UTC
Labels: hip
